title: Syed Muhammad Shaheer Zaidi # your name (or website title) here
logo: "images/7ea2bd621e649450e4b9513baa6bd931.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a junior studying Computer Science at York University. I am looking for a coop/internship opportunity. I am a fast learner, and love to learn new technologies and skills. 
  <br><br>
  
  <a href="https://drive.google.com/file/d/1hNEWIX1vSCCB03cDm-irugW5Eb8AXPFI/view?usp=sharing">View My Resume</a> 
  <br>
  <br>
  <a href="https://www.linkedin.com/in/syed-muhammad-shaheer-zaidi-992a07140/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
